services:
  vtiger:
    build: .
    container_name: omnir_crm_app
    restart: always
    user: "1000:1000"
    ports:
      - "8080:80"
    environment:
      - VT_DB_HOST=db
      - VT_DB_NAME=teamguy2000
      - VT_DB_USER=teamguy2000
      - VT_DB_PASSWORD=teamguy2000
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: omnir_crm_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=teamguy2000
      - MYSQL_DATABASE=teamguy2000
      - MYSQL_USER=teamguy2000
      - MYSQL_PASSWORD=teamguy2000
    volumes:
      - ./db-data:/var/lib/mysql
