services:
  vtiger:
    build: .
    container_name: omnir_crm_app
    restart: always
    ports:
      - "8080:80"
    environment:
      - VT_DB_HOST=db
      - VT_DB_NAME=vtiger_crm
      - VT_DB_USER=vtiger_user
      - VT_DB_PASSWORD=vtiger_password
    volumes:
      - ./vtiger-data:/var/www/html
      - ./vtigercrm8.4.0.tar.gz:/tmp/vtiger.tar
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: omnir_crm_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=vtiger_crm
      - MYSQL_USER=vtiger_user
      - MYSQL_PASSWORD=vtiger_password
    volumes:
      - ./db-data:/var/lib/mysql
      # Automatically seeds the database for new environments
      - ./vtiger_base_setup.sql:/docker-entrypoint-initdb.d/setup.sql