services:
  vtiger:
    build: .
    container_name: omnir_crm_app
    ports:
      - "8080:80"
    environment:
      - VT_DB_HOST=db
      - VT_DB_NAME=teamguy2000
      - VT_DB_USER=teamguy2000
      - VT_DB_PASSWORD=teamguy2000
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    container_name: omnir_crm_db
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --sql-mode="ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    environment:
      - MYSQL_ROOT_PASSWORD=teamguy2000
      - MYSQL_DATABASE=teamguy2000
      - MYSQL_USER=teamguy2000
      - MYSQL_PASSWORD=teamguy2000
    volumes:
      - ./db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-pteamguy2000" ]
      interval: 5s
      timeout: 5s
      retries: 10
